# -*- coding: utf-8 -*-
"""Aula Python relatorio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bzvdVp-SJ8f2_7_RPpyliGUlg14l0pAB
"""

!pip install pdf_reports -q

import pandas as pd
from datetime import datetime 
from pdf_reports import pug_to_html, write_report

planilha = pd.read_excel("/content/controle_de_abacates_atualizado.xlsx")

planilha

hoje = datetime.now().date()

hoje

html = pug_to_html("/content/modelo_de_relatorio.pug",
                   planilha=planilha,
                   hoje=hoje)

write_report(html,'controle_abacates_reletorio2.pdf')